// <auto-generated />
using System;
using BolsaEmpleos.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BolsaEmpleos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BolsaEmpleosDbContext))]
    partial class BolsaEmpleosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("JovenId")
                        .HasColumnType("integer")
                        .HasColumnName("joven_id");

                    b.Property<string>("ResumenProfesional")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resumen_profesional");

                    b.Property<string>("TituloProfesional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo_profesional");

                    b.Property<string>("UrlPortfolio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_portfolio");

                    b.HasKey("Id");

                    b.HasIndex("JovenId")
                        .IsUnique();

                    b.ToTable("curricula", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.CurriculumHabilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer")
                        .HasColumnName("curriculum_id");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_agregado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidad_id");

                    b.Property<bool>("ObtenidaPorCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("obtenida_por_curso");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("CurriculumId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("curriculum_habilidades", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("DuracionHoras")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("duracion_horas");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidad_id");

                    b.Property<int>("PuntajeMinimoAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(70)
                        .HasColumnName("puntaje_minimo_aprobacion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlMaterial")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_material");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sitio_web");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos");

                    b.Property<int>("JovenId")
                        .HasColumnType("integer")
                        .HasColumnName("joven_id");

                    b.Property<int?>("PuntajeObtenido")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_obtenido");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("JovenId");

                    b.ToTable("evaluaciones", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("habilidades", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Joven", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo_electronico");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("NivelEducativo")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_educativo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.ToTable("jovenes", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.OfertaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal?>("Salario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ofertas_trabajo", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_postulacion");

                    b.Property<int>("JovenId")
                        .HasColumnType("integer")
                        .HasColumnName("joven_id");

                    b.Property<int>("OfertaTrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("oferta_trabajo_id");

                    b.HasKey("Id");

                    b.HasIndex("OfertaTrabajoId");

                    b.HasIndex("JovenId", "OfertaTrabajoId")
                        .IsUnique();

                    b.ToTable("postulaciones", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Requisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("HabilidadId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidad_id");

                    b.Property<int>("OfertaTrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("oferta_trabajo_id");

                    b.Property<int>("TipoRequisito")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_requisito");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("OfertaTrabajoId");

                    b.ToTable("requisitos", (string)null);
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curriculum", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Joven", "Joven")
                        .WithOne("Curriculum")
                        .HasForeignKey("BolsaEmpleos.Domain.Entities.Curriculum", "JovenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joven");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.CurriculumHabilidad", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("CurriculumHabilidades")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaEmpleos.Domain.Entities.Habilidad", "Habilidad")
                        .WithMany("CurriculumHabilidades")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Habilidad");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curso", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Habilidad", "Habilidad")
                        .WithMany("Cursos")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habilidad");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Curso", "Curso")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolsaEmpleos.Domain.Entities.Joven", "Joven")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("JovenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Joven");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.OfertaTrabajo", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Empresa", "Empresa")
                        .WithMany("OfertasTrabajo")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Postulacion", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Joven", "Joven")
                        .WithMany("Postulaciones")
                        .HasForeignKey("JovenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaEmpleos.Domain.Entities.OfertaTrabajo", "OfertaTrabajo")
                        .WithMany("Postulaciones")
                        .HasForeignKey("OfertaTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Joven");

                    b.Navigation("OfertaTrabajo");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Requisito", b =>
                {
                    b.HasOne("BolsaEmpleos.Domain.Entities.Habilidad", "Habilidad")
                        .WithMany("Requisitos")
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolsaEmpleos.Domain.Entities.OfertaTrabajo", "OfertaTrabajo")
                        .WithMany("Requisitos")
                        .HasForeignKey("OfertaTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("OfertaTrabajo");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("CurriculumHabilidades");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("OfertasTrabajo");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Habilidad", b =>
                {
                    b.Navigation("CurriculumHabilidades");

                    b.Navigation("Cursos");

                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.Joven", b =>
                {
                    b.Navigation("Curriculum");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("BolsaEmpleos.Domain.Entities.OfertaTrabajo", b =>
                {
                    b.Navigation("Postulaciones");

                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
